added async write flag for ADIOS2
openPMD/openPMD-api pull request #1460
Opened 2023-06-13 20:25 UTC by guj

2023-06-13 21:07 UTC, guj commented
Hi @franzpoeschel @ax3l 

Any idea why the test fail with hdf5 on Conda_ompi_all fails on ?

2023-06-14 16:43 UTC, franzpoeschel commented on src/IO/ADIOS/ADIOS2IOHandler.cpp
> +            if (1 == auxiliary::getEnvNum("OPENPMD_ADIOS2_ASYNC_WRITE", 1) &&
```suggestion
            if (1 == auxiliary::getEnvNum("OPENPMD_ADIOS2_ASYNC_WRITE", 0) &&
```

Your change would activate async write by default. This probably explains the failing CI run, too.

2023-06-14 16:48 UTC, franzpoeschel requested changes
Can you please document the additional parameter in `adios2.rst`?

Also, note that in BP5, openPMD will flush to disk by default which makes no sense in combination with async I/O. So, if you add an environment variable for this, it probably makes sense to flip that default in this case.

2023-06-20 05:32 UTC, guj commented
> Can you please document the additional parameter in `adios2.rst`?
> 
Will do
> Also, note that in BP5, openPMD will flush to disk by default which makes no sense in combination with async I/O. So, if you add an environment variable for this, it probably makes sense to flip that default in this case.

Yes, I had to flip the  PerformDataWrite.  I wonder whether this should an option as well.

2023-06-20 09:01 UTC, franzpoeschel commented
> Yes, I had to flip the PerformDataWrite. I wonder whether this should an option as well.

I think that we don't need an extra option for this. I added a commit that sets the default flush target to the Buffer when using this env var.

2023-06-20 15:46 UTC, franzpoeschel approved these changes
LGTM
The failing docs PR run concerns all PRs currently and has nothing to do with this PR.

2023-06-20 16:29 UTC, guj commented
> LGTM
> The failing docs PR run concerns all PRs currently and has nothing to do with this PR.



> > Yes, I had to flip the PerformDataWrite. I wonder whether this should an option as well.
> 
> I think that we don't need an extra option for this. I added a commit that sets the default flush target to the Buffer when using this env var.

That will do. Thanks.

2023-06-21 13:30 UTC, merged