Python: Series to DataFrame
openPMD/openPMD-api pull request #1506
Opened 2023-08-16 20:10 UTC by ax3l

Add new helpers to create Pandas and cuDF dataframes for a single particle species, over all iterations at once.

- [ ] add tests

2024-08-01 15:04 UTC, franzpoeschel requested changes
There are two small hardcoded parameters that you probably meant to replace still.
Looks good otherwise, thank you!

2024-08-01 15:04 UTC, franzpoeschel commented on src/binding/python/openpmd_api/DataFrame.py
> +            .particles["electrons"]
```suggestion
            .particles[species_name]
```

2024-08-01 15:04 UTC, franzpoeschel commented on src/binding/python/openpmd_api/DataFrame.py
> +                      .particles["electrons"]
```suggestion
                      .particles[species_name]
```

2024-08-01 17:28 UTC, ax3l commented on src/binding/python/openpmd_api/DataFrame.py
> +            .particles["electrons"]
Good catch!

2024-08-01 17:31 UTC, ax3l commented
Ouch, good catch! Thank you, fixed now.

2024-08-05 17:42 UTC, franzpoeschel approved these changes

2024-08-05 17:42 UTC, merged