setshape() should not touch the joined dim
openPMD/openPMD-api pull request #1656
Opened 2024-08-01 06:12 UTC by guj

if a joined dim exists, setshape() should not change it.

2024-08-01 14:40 UTC, franzpoeschel commented
Do you have a specific use case in mind for this?
If yes, can you add that as a test, please?

If there is no specific use case, should we maybe rather just check this and throw an error if the shape is changed in unconventional ways?

Also, I think that this logic is more adequately placed in the frontend at `RecordComponent::resetDataset()`, since there is nothing inherently ADIOS2-specific about it.

2024-08-01 14:46 UTC, franzpoeschel requested changes

2024-08-01 14:46 UTC, franzpoeschel commented on src/IO/ADIOS/ADIOS2IOHandler.cpp
> -            var.SetShape(shape);
I don't think that the previous `shape` should be considered here at all.
This code is executed when the Variable was already part of the previous step. The Variable shape can be something completely new in the new step. If the user means to use a joined dimension again, `Dataset::JOINED_DIMENSION` should be specified again; we should not try to outsmart the user by trying to keep the joined dimension from the previous step.

2024-08-01 14:46 UTC, franzpoeschel commented on src/IO/ADIOS/ADIOS2IOHandler.cpp
> +                dims[idx] = var.Shape()[idx];
Undefined behavior if the vector lengths are not the same

2024-08-01 17:01 UTC, guj commented
> Do you have a specific use case in mind for this? If yes, can you add that as a test, please?
> 
> If there is no specific use case, should we maybe rather just check this and throw an error if the shape is changed in unconventional ways?
> 
> Also, I think that this logic is more adequately placed in the frontend at `RecordComponent::resetDataset()`, since there is nothing inherently ADIOS2-specific about it.

Yes, this change was needed when testing joined dimension in warpx.  Let me see if I can come up with a test case.

2024-09-05 17:36 UTC, ax3l commented
@guj can you please add a tiny test case for this that covers joined arrays with constant record components?
That way, @franzpoeschel can review this easier and we can cover that this works going forward.

2025-06-03 12:16 UTC, franzpoeschel commented
This has been fixed with #1740, I think? Feel free to reopen, if not.

2025-06-03 12:16 UTC, closed without merging